### ISSUE TITLE
Check if nickname is already taken

### ISSUE THREAD

**Issue by antoine-pous** [voicis/nodebb-plugin-sso-battle.net#3]
When user login with Battlenet for the first time the forum ask for email and username.

I don't know if this issue is really related to your plugin, but it should validate the nickname. Any user can use staff usernames.

In fact this is a real another account, but this could quickly become dangerous when malicious users comes for making phishing attack.

Can your add an option or force the nickname to be unique?

**Comment by voicis** [comment]
Added username and email uniqueness checks on registration. It should not be possible to enter duplicate user names anymore.
